# Generated by Django 5.2.7 on 2025-10-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_fill_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('raw', 'Необработанный'), ('inprogress', 'В работе'), ('delivery', 'Доставка'), ('completed', 'Завершен')], db_index=True, default='raw', max_length=20, verbose_name='Статус'),
        ),
    ]
