# Generated by Django 5.2.7 on 2025-10-26 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 10, 20, 45, 128465, tzinfo=datetime.timezone.utc), verbose_name='Дата оформления'),
        ),
    ]
