# Generated by Django 5.2.7 on 2025-10-26 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличными'), ('electronic', 'Электронно')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 10, 32, 59, 189825, tzinfo=datetime.timezone.utc), verbose_name='Дата оформления'),
        ),
    ]
