# Generated by Django 5.2.7 on 2025-10-26 17:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_payment_type_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 17, 39, 23, 40728, tzinfo=datetime.timezone.utc), verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('electronic', 'Электронно')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
