# Generated by Django 5.2.7 on 2025-10-25 00:02

from django.db import migrations, transaction, models


def copy_product_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    with transaction.atomic():
        for item in OrderItem.objects.select_related('product').iterator():
            item.price = item.product.price
            item.save(update_fields=['price'])

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(copy_product_price, migrations.RunPython.noop),
    ]
